#!/usr/bin/env python3
"""
analyze_dep_closure.py
Full dependency graph analysis: schema validation, ID normalization,
orphan detection, cycle detection (SCC), hub analysis, bidirectional pair detection.

This is the single highest-value deterministic tool in the system. It consolidates
graph analysis that was previously regenerated by the LLM on every reconciliation run.

Usage:
    python3 analyze_dep_closure.py <EXECUTION_ROOT> [--output-dir <path>]

Inputs:
    EXECUTION_ROOT — Path to project execution root
    --output-dir   — Where to write output CSVs (default: stdout summary only)

Outputs (when --output-dir specified):
    closure_summary.json     — Aggregate statistics
    orphans.csv              — Deliverables with no dependencies
    scc_summary.csv          — Strongly connected components
    hubs.csv                 — High-degree nodes (degree >= threshold)
    bidirectional_pairs.csv  — Edges that exist in both directions
    coverage.csv             — Per-deliverable dependency file presence
    id_normalization.csv     — IDs that required normalization

Example:
    python3 analyze_dep_closure.py ./execution --output-dir ./closure_report
"""

import csv
import glob
import json
import os
import re
import sys
from collections import defaultdict

# --- Configuration ---
REQUIRED_COLUMNS = [
    "RegisterSchemaVersion", "DependencyID", "FromPackageID", "FromDeliverableID",
    "FromDeliverableName", "DependencyClass", "AnchorType", "Direction",
    "DependencyType", "TargetType", "TargetPackageID", "TargetDeliverableID",
    "TargetRefID", "TargetName", "TargetLocation", "Statement",
    "EvidenceFile", "SourceRef", "EvidenceQuote", "Explicitness",
    "RequiredMaturity", "ProposedMaturity", "SatisfactionStatus", "Confidence",
    "Origin", "FirstSeen", "LastSeen", "Status", "Notes"
]
HUB_THRESHOLD = 20
DEL_PATTERN = re.compile(r'^DEL-\d{3}-\d{2}$')
PKG_PATTERN = re.compile(r'^PKG-\d{3}$')


def find_dependency_csvs(execution_root):
    """Find all Dependencies.csv files under 1_Working/DEL-* folders."""
    pattern = os.path.join(execution_root, "PKG-*", "1_Working", "DEL-*", "Dependencies.csv")
    return sorted(glob.glob(pattern))


def normalize_id(raw_id):
    """Normalize a deliverable or package ID to canonical format."""
    if not raw_id:
        return raw_id, False
    cleaned = raw_id.strip()
    if DEL_PATTERN.match(cleaned) or PKG_PATTERN.match(cleaned):
        return cleaned, False
    # Try to normalize common variations
    normalized = cleaned
    return normalized, normalized != raw_id


def validate_schema(header):
    """Check if header contains all required v3.1 columns."""
    header_clean = [col.strip().lstrip('\ufeff') for col in header]
    missing = [col for col in REQUIRED_COLUMNS if col not in header_clean]
    return missing, header_clean


def load_all_edges(csv_paths):
    """Load all dependency rows from all CSV files."""
    all_rows = []
    schema_results = {}
    normalizations = []

    for path in csv_paths:
        with open(path, 'r', newline='') as f:
            reader = csv.DictReader(f)
            fieldnames = reader.fieldnames or []
            missing, clean_header = validate_schema(fieldnames)
            del_dir = os.path.basename(os.path.dirname(path))
            del_id = del_dir.split('_')[0]

            schema_results[del_id] = {
                'path': path,
                'missing_columns': missing,
                'valid': len(missing) == 0,
                'column_count': len(fieldnames)
            }

            for row in reader:
                # Normalize IDs
                from_id = (row.get('FromDeliverableID') or '').strip()
                target_id = (row.get('TargetDeliverableID') or '').strip()

                norm_from, changed_from = normalize_id(from_id)
                norm_target, changed_target = normalize_id(target_id)

                if changed_from:
                    normalizations.append({'original': from_id, 'normalized': norm_from, 'field': 'FromDeliverableID', 'file': path})
                if changed_target:
                    normalizations.append({'original': target_id, 'normalized': norm_target, 'field': 'TargetDeliverableID', 'file': path})

                row['_source_file'] = path
                row['_from_id_norm'] = norm_from
                row['_target_id_norm'] = norm_target
                all_rows.append(row)

    return all_rows, schema_results, normalizations


def build_graph(rows):
    """Build adjacency lists from EXECUTION class, ACTIVE status, DELIVERABLE target rows."""
    graph = defaultdict(set)  # forward edges
    reverse = defaultdict(set)  # reverse edges
    all_nodes = set()

    for row in rows:
        dep_class = (row.get('DependencyClass') or '').strip()
        status = (row.get('Status') or '').strip()
        target_type = (row.get('TargetType') or '').strip()

        if dep_class != 'EXECUTION' or status != 'ACTIVE' or target_type != 'DELIVERABLE':
            continue

        from_id = row['_from_id_norm']
        target_id = row['_target_id_norm']
        direction = (row.get('Direction') or '').strip()

        if not from_id or not target_id:
            continue

        all_nodes.add(from_id)
        all_nodes.add(target_id)

        if direction == 'UPSTREAM':
            graph[from_id].add(target_id)
            reverse[target_id].add(from_id)
        elif direction == 'DOWNSTREAM':
            graph[target_id].add(from_id)
            reverse[from_id].add(target_id)

    return graph, reverse, all_nodes


def find_sccs(graph, nodes):
    """Tarjan's algorithm for strongly connected components."""
    index_counter = [0]
    stack = []
    lowlink = {}
    index = {}
    on_stack = {}
    sccs = []

    def strongconnect(v):
        index[v] = index_counter[0]
        lowlink[v] = index_counter[0]
        index_counter[0] += 1
        stack.append(v)
        on_stack[v] = True

        for w in graph.get(v, []):
            if w not in index:
                strongconnect(w)
                lowlink[v] = min(lowlink[v], lowlink[w])
            elif on_stack.get(w, False):
                lowlink[v] = min(lowlink[v], index[w])

        if lowlink[v] == index[v]:
            scc = []
            while True:
                w = stack.pop()
                on_stack[w] = False
                scc.append(w)
                if w == v:
                    break
            if len(scc) > 1:
                sccs.append(sorted(scc))

    for node in sorted(nodes):
        if node not in index:
            strongconnect(node)

    return sccs


def find_orphans(graph, reverse, all_deliverable_ids):
    """Find deliverables with no execution edges in either direction."""
    connected = set(graph.keys()) | set(reverse.keys())
    for targets in graph.values():
        connected |= targets
    for sources in reverse.values():
        connected |= sources
    return sorted(all_deliverable_ids - connected)


def find_hubs(graph, reverse, threshold):
    """Find nodes with total degree >= threshold."""
    degrees = defaultdict(lambda: {'in': 0, 'out': 0})
    for node, targets in graph.items():
        degrees[node]['out'] += len(targets)
        for t in targets:
            degrees[t]['in'] += 1

    hubs = []
    for node, deg in sorted(degrees.items()):
        total = deg['in'] + deg['out']
        if total >= threshold:
            hubs.append({'node': node, 'in_degree': deg['in'], 'out_degree': deg['out'], 'total': total})

    return sorted(hubs, key=lambda x: -x['total'])


def find_bidirectional_pairs(graph):
    """Find pairs where A→B and B→A both exist."""
    pairs = set()
    for a, targets in graph.items():
        for b in targets:
            if a in graph.get(b, set()):
                pair = tuple(sorted([a, b]))
                pairs.add(pair)
    return sorted(pairs)


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <EXECUTION_ROOT> [--output-dir <path>]", file=sys.stderr)
        sys.exit(1)

    execution_root = sys.argv[1]
    output_dir = None

    if '--output-dir' in sys.argv:
        idx = sys.argv.index('--output-dir')
        if idx + 1 < len(sys.argv):
            output_dir = sys.argv[idx + 1]
            os.makedirs(output_dir, exist_ok=True)

    # Find all Dependencies.csv files
    csv_paths = find_dependency_csvs(execution_root)
    print(f"Found {len(csv_paths)} Dependencies.csv files")

    # Load all edges
    all_rows, schema_results, normalizations = load_all_edges(csv_paths)
    print(f"Loaded {len(all_rows)} total dependency rows")

    # Schema validation summary
    valid_count = sum(1 for r in schema_results.values() if r['valid'])
    invalid_count = len(schema_results) - valid_count
    print(f"Schema: {valid_count} valid, {invalid_count} invalid")

    # Count by class
    anchor_count = sum(1 for r in all_rows if (r.get('DependencyClass') or '').strip() == 'ANCHOR')
    exec_count = sum(1 for r in all_rows if (r.get('DependencyClass') or '').strip() == 'EXECUTION')
    print(f"ANCHOR rows: {anchor_count}, EXECUTION rows: {exec_count}")

    # Check IMPLEMENTS_NODE coverage
    has_implements = set()
    for row in all_rows:
        if (row.get('AnchorType') or '').strip() == 'IMPLEMENTS_NODE':
            has_implements.add(row['_from_id_norm'])
    missing_implements = len(schema_results) - len(has_implements)
    print(f"IMPLEMENTS_NODE: {len(has_implements)} present, {missing_implements} missing")

    # Check evidence coverage
    evidence_total = len(all_rows)
    evidence_populated = sum(1 for r in all_rows if (r.get('EvidenceFile') or '').strip())
    print(f"Evidence coverage: {evidence_populated}/{evidence_total}")

    # Build graph (EXECUTION edges only)
    graph, reverse, all_nodes = build_graph(all_rows)
    edge_count = sum(len(targets) for targets in graph.values())
    print(f"Graph: {len(all_nodes)} nodes, {edge_count} edges")

    # All deliverable IDs from filesystem
    all_del_ids = set(schema_results.keys())

    # Analysis
    orphans = find_orphans(graph, reverse, all_del_ids)
    sccs = find_sccs(graph, all_nodes)
    hubs = find_hubs(graph, reverse, HUB_THRESHOLD)
    bidir_pairs = find_bidirectional_pairs(graph)

    print(f"Orphans: {len(orphans)}")
    print(f"SCCs (size > 1): {len(sccs)}")
    if sccs:
        for i, scc in enumerate(sccs):
            print(f"  SCC-{i+1:03d}: {len(scc)} nodes")
    print(f"Hubs (degree >= {HUB_THRESHOLD}): {len(hubs)}")
    print(f"Bidirectional pairs: {len(bidir_pairs)}")
    print(f"ID normalizations: {len(normalizations)}")

    # Write output files if output_dir specified
    if output_dir:
        # closure_summary.json
        summary = {
            'total_files': len(csv_paths),
            'total_rows': len(all_rows),
            'anchor_rows': anchor_count,
            'execution_rows': exec_count,
            'schema_valid': valid_count,
            'schema_invalid': invalid_count,
            'implements_node_present': len(has_implements),
            'implements_node_missing': missing_implements,
            'evidence_populated': evidence_populated,
            'evidence_total': evidence_total,
            'graph_nodes': len(all_nodes),
            'graph_edges': edge_count,
            'orphan_count': len(orphans),
            'scc_count': len(sccs),
            'scc_sizes': [len(s) for s in sccs],
            'hub_count': len(hubs),
            'bidirectional_pair_count': len(bidir_pairs),
            'normalization_count': len(normalizations),
        }
        with open(os.path.join(output_dir, 'closure_summary.json'), 'w') as f:
            json.dump(summary, f, indent=2)

        # orphans.csv
        with open(os.path.join(output_dir, 'orphans.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['DeliverableID'])
            for o in orphans:
                writer.writerow([o])

        # scc_summary.csv
        with open(os.path.join(output_dir, 'scc_summary.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['SCC_ID', 'Size', 'Nodes'])
            for i, scc in enumerate(sccs):
                writer.writerow([f'SCC-{i+1:03d}', len(scc), ';'.join(scc)])

        # hubs.csv
        with open(os.path.join(output_dir, 'hubs.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['DeliverableID', 'InDegree', 'OutDegree', 'TotalDegree'])
            for h in hubs:
                writer.writerow([h['node'], h['in_degree'], h['out_degree'], h['total']])

        # bidirectional_pairs.csv
        with open(os.path.join(output_dir, 'bidirectional_pairs.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['NodeA', 'NodeB'])
            for a, b in bidir_pairs:
                writer.writerow([a, b])

        # coverage.csv
        with open(os.path.join(output_dir, 'coverage.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['DeliverableID', 'HasDependencyCsv', 'RowCount', 'SchemaValid', 'HasImplementsNode'])
            for del_id in sorted(all_del_ids):
                info = schema_results[del_id]
                row_count = sum(1 for r in all_rows if r['_from_id_norm'] == del_id)
                has_impl = 'Y' if del_id in has_implements else 'N'
                writer.writerow([del_id, 'Y', row_count, 'Y' if info['valid'] else 'N', has_impl])

        # id_normalization.csv
        with open(os.path.join(output_dir, 'id_normalization.csv'), 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['Original', 'Normalized', 'Field', 'File'])
            for n in normalizations:
                writer.writerow([n['original'], n['normalized'], n['field'], n['file']])

        print(f"\nOutputs written to: {output_dir}")


if __name__ == '__main__':
    main()
